ports:
  - port: 8080
tasks:
  - init: mysql < DDL.sql && mysql < mock_usu_usuario.sql
  - command: sudo docker-up
  - command: sleep 15
  - command: docker run rabbitmq
image: gitpod/workspace-mysql
